<?php
$config = array(
	'admin' => array('edit'),
	'catalognew' => array('index', 'add', 'edit', 'delete', 'del_all', 'an_hien', 'noi_bat'),
	'news' => array('index', 'add', 'edit', 'delete', 'del_all', 'an_hien', 'noi_bat'),
	'menu' => array('index', 'add', 'edit', 'delete', 'del_all', 'load_menu_ajax'),
	// 'side' => array('index', 'add', 'edit', 'delete', 'del_all', 'load_menu_ajax'),
	'trang' => array('index', 'add', 'edit', 'delete', 'del_all', 'an_hien'),
	'setting' => array('index'),
	'slide' => array('index', 'add', 'edit', 'delete', 'del_all'),
	'deletecache' => array('index'),
	// 'donhang' => array('index', 'edit', 'inhoadon', 'delete', 'del_all'),
	'lienhe' => array('index', 'traloi', 'delete'),
	'emailtintuc' => array('index', 'delete', 'del_all'),
	// 'tinhthanh' => array('index', 'add', 'edit', 'delete', 'del_all'),
	// 'quanhuyen' => array('index', 'add', 'edit', 'delete', 'del_all'),
	'catalog' => array('index', 'add', 'edit', 'delete', 'del_all', 'an_hien'),
	'product' => array('index', 'add', 'edit', 'delete', 'del_all', 'sp_an_hien','sp_new','sp_noi_bat'),
	// 'color' => array('index', 'add', 'edit', 'delete', 'del_all'),
	'hotrotructuyen' => array('index', 'add', 'edit', 'delete', 'del_all'),
	// 'ykien' => array('index', 'add', 'edit', 'delete', 'del_all'),
	// 'loaiphong' => array('index', 'add', 'edit', 'delete', 'del_all'),
	// 'logodoitac' => array('index', 'add', 'edit', 'delete', 'del_all'),
	// 'thongketruycap' => array('index'),
);